server:
  port: 8000
  servlet:
    context-path: /v1/juguetes/api
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/juguetes
#    username: root
#    password: 1234567
spring:
  datasource:
    driver:
      class: com.mysql.jdbc.Driver